import { flushPromises, mount } from '@vue/test-utils'
import { afterEach, expect, it, vi } from 'vitest'
import HpmUserOtpPanel from './HpmUserOtpPanel.vue'
afterEach(() => vi.unstubAllGlobals())
it('previews the exact permanent group and invalidates confirmation when it changes', async () => {
  const fetch = vi.fn()
    .mockResolvedValueOnce({ok:true,json:async()=>({words:[],hard_lock:0x30400016})})
    .mockResolvedValueOnce({ok:true,json:async()=>({word:0,group:19,expected:0x30400016,desired:0x30480016,delta:0x80000,script:'lock group 19'})})
  vi.stubGlobal('fetch',fetch)
  const w=mount(HpmUserOtpPanel,{props:{partNumber:'HPM5301',model:'V4'}})
  await w.get('[aria-label="OTP operation"]').setValue('lock')
  expect(w.get('[data-testid=otp-plan]').attributes('disabled')).toBeDefined()
  await w.get('[data-testid=otp-read]').trigger('click');await flushPromises()
  await w.get('[data-testid=otp-plan]').trigger('click');await flushPromises()
  expect(fetch.mock.calls[1]![0]).toContain('/lock-plan')
  expect(JSON.parse(fetch.mock.calls[1]![1].body)).toMatchObject({word:19,expected:0x30400016})
  expect(w.text()).toContain('76–79')
  await w.get('[data-testid=otp-confirm]').setValue(true)
  await w.get('[aria-label="OTP lock group"]').setValue('18')
  expect(w.find('[data-testid=otp-program]').exists()).toBe(false)
  expect(fetch).toHaveBeenCalledTimes(2)
  w.unmount()
})

it('requires read, preview and explicit confirmation; edits invalidate the plan', async () => {
  const fetch = vi.fn().mockResolvedValueOnce({ ok: true, json: async () => ({ words: [{ word: 69, current: 1, shadow: 1, locked: false }] }) })
    .mockResolvedValueOnce({ ok: true, json: async () => ({ word:69, expected:1, desired:3, delta:2, script:'guarded script' }) })
  vi.stubGlobal('fetch', fetch)
  const w = mount(HpmUserOtpPanel, { props:{ partNumber:'HPM5301',model:'V4' } })
  expect(fetch).not.toHaveBeenCalled()
  expect(w.get('[data-testid=otp-plan]').attributes('disabled')).toBeDefined()
  await w.get('[data-testid=otp-read]').trigger('click'); await flushPromises()
  await w.get('[aria-label="OTP desired value"]').setValue('0x3')
  await w.get('[data-testid=otp-plan]').trigger('click'); await flushPromises()
  expect(w.get('[data-testid=otp-program]').attributes('disabled')).toBeDefined()
  await w.get('[data-testid=otp-confirm]').setValue(true)
  expect(w.get('[data-testid=otp-program]').attributes('disabled')).toBeUndefined()
  await w.get('[aria-label="OTP desired value"]').setValue('0x7')
  expect(w.find('[data-testid=otp-program]').exists()).toBe(false)
  expect(fetch).toHaveBeenCalledTimes(2)
  w.unmount()
})

it('posts a confirmed plan only once and requires fresh reads after an unknown outcome', async () => {
  let finish!: (value: unknown) => void
  const fetch = vi.fn()
    .mockResolvedValueOnce({ok:true,json:async()=>({words:[{word:69,current:1,shadow:1,locked:false}]})})
    .mockResolvedValueOnce({ok:true,json:async()=>({word:69,expected:1,desired:3,delta:2,script:'script'})})
    .mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve}))
  vi.stubGlobal('fetch',fetch)
  const w=mount(HpmUserOtpPanel,{props:{partNumber:'HPM5301',model:'V4'}})
  await w.get('[data-testid=otp-read]').trigger('click');await flushPromises()
  await w.get('[aria-label="OTP desired value"]').setValue('3')
  await w.get('[data-testid=otp-plan]').trigger('click');await flushPromises()
  await w.get('[data-testid=otp-confirm]').setValue(true)
  await w.get('[data-testid=otp-program]').trigger('click')
  await w.get('[data-testid=otp-program]').trigger('click')
  expect(fetch).toHaveBeenCalledTimes(3)
  expect(JSON.parse(fetch.mock.calls[2]![1].body)).toMatchObject({word:69,expected:1,desired:3,confirm_irreversible:true})
  finish({ok:false,json:async()=>({detail:'lost response'})});await flushPromises()
  expect(w.get('[role=alert]').text()).toContain('不要重试')
  expect(w.find('[data-testid=otp-program]').exists()).toBe(false)
  expect(w.get('[data-testid=otp-plan]').attributes('disabled')).toBeDefined()
  w.unmount()
})

it('explains rejected bit clearing without offering a program action', async () => {
  vi.stubGlobal('fetch', vi.fn()
    .mockResolvedValueOnce({ok:true,json:async()=>({words:[{word:69,current:7,shadow:7,locked:false}]})})
    .mockResolvedValueOnce({ok:false,json:async()=>({detail:'OTP bits cannot be cleared (1 to 0)'})}))
  const w=mount(HpmUserOtpPanel,{props:{partNumber:'HPM5301',model:'V4'}})
  await w.get('[data-testid=otp-read]').trigger('click');await flushPromises()
  await w.get('[aria-label="OTP desired value"]').setValue('1')
  await w.get('[data-testid=otp-plan]').trigger('click');await flushPromises()
  expect(w.get('[role=alert]').text()).toContain('OTP不能擦除')
  expect(w.find('[data-testid=otp-program]').exists()).toBe(false)
  w.unmount()
})

it('reports the locked user range rather than an unexplained word zero', async () => {
  vi.stubGlobal('fetch', vi.fn()
    .mockResolvedValueOnce({ok:true,json:async()=>({words:[],hard_lock:0x30400016})})
    .mockResolvedValueOnce({ok:true,json:async()=>({word:0,group:19,expected:0x30400016,desired:0x30480016,delta:0x80000,script:'lock'})})
    .mockResolvedValueOnce({ok:true,json:async()=>({word:0,after:0x30480016})}))
  const w=mount(HpmUserOtpPanel,{props:{partNumber:'HPM5301',model:'V4'}})
  await w.get('[aria-label="OTP operation"]').setValue('lock')
  await w.get('[data-testid=otp-read]').trigger('click');await flushPromises()
  await w.get('[data-testid=otp-plan]').trigger('click');await flushPromises()
  await w.get('[data-testid=otp-confirm]').setValue(true)
  await w.get('[data-testid=otp-program]').trigger('click');await flushPromises()
  expect(w.get('[role=status]').text()).toContain('Word 76–79')
  expect(w.get('[role=status]').text()).toContain('HARD_LOCK = 0x30480016')
  w.unmount()
})
